services:
  outer-caddy:
    container_name: outer-caddy
    image: mycaddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./outer-caddy/conf:/etc/caddy
      - outer_caddy_data:/data
      - outer_caddy_config:/config
    # mem_limit: 256m
    # cpu_shares: 512
    networks:
      - caddy
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    pull_policy: always
    environment:
      BIND: ":3000"
      TARGET: http://inner-caddy
    networks:
      - caddy
  inner-caddy:
    container_name: inner-caddy
    image: mycaddy
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./inner-caddy/conf:/etc/caddy
      - inner_caddy_data:/data
      - inner_caddy_config:/config
      - docs:/var/www/docs
    # mem_limit: 256m
    # cpu_shares: 512
    networks:
      - caddy
      - hsjs
      - vaultwarden
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "2000:80/tcp"
      - "2001:443/tcp"
      - "67:67/udp"
      - "123:123/udp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    environment:
      TZ: "Europe/Oslo"
      FTLCONF_dns_upstreams: 1.1.1.1;8.8.8.8;8.8.4.4

      FTLCONF_webserver_api_password: ${PIHOLE_ADMIN_PASSWORD}
      FTLCONF_dns_listeningMode: "ALL"
    volumes:
      - ./etc-pihole/:/etc/piehole
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
  minecraft:
    image: marctv/minecraft-papermc-server:1.21.10
    restart: unless-stopped
    container_name: minecraft-server
    environment:
      MEMORYSIZE: "1G"
      PAPERMC_FLAGS: ""
    volumes:
      - ./minecraft:/data
    ports:
      - 25565:25565
    stdin_open: true
    tty: true
networks:
  caddy:
    name: caddy
  nextcloud-aio:
    external: true
  hsjs:
    external: true
  vaultwarden:
    external: true
volumes:
  outer_caddy_data:
  outer_caddy_config:
  inner_caddy_data:
  inner_caddy_config:
  docs:
    external: true
