services:
  caddy:
    image: mycaddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./caddy/conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
      - docs:/var/www/docs
    # mem_limit: 256m
    # cpu_shares: 512
    networks:
      - caddy
      - nextcloud-aio
      - hsjs
      - vaultwarden
  minecraft:
    image: marctv/minecraft-papermc-server:1.21.10
    restart: unless-stopped
    container_name: minecraft-server
    environment:
      MEMORYSIZE: "1G"
      PAPERMC_FLAGS: ""
    volumes:
      - ./minecraft:/data
    ports:
      - 25565:25565
    stdin_open: true
    tty: true
networks:
  caddy:
    name: caddy
  nextcloud-aio:
    external: true
  hsjs:
    external: true
  vaultwarden:
    external: true
volumes:
  caddy_data:
  caddy_config:
  docs:
    external: true
